version: '3'

services:
  dpng-1:
    image: papadoxie/cca03m01:latest
    ports:
      - 1337:1337
    
  dpng-2:
    image: papadoxie/cca03m01:latest
    ports:
      - 1338:1337

  dpng-3:
    image: papadoxie/cca03m01:latest
    ports:
      - 1339:1337

  master:
    image: papadoxie/cca03m03:latest
    links:
      - dpng-1
      - dpng-2
      - dpng-3
    depends_on:
      - dpng-1
      - dpng-2
      - dpng-3
    restart: on-failure
